name: 'CI Deploy App to S3'

on:
  push:
    branches:
      - main

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Lister les fichiers et dossiers
      run: |
        ls -la
   